### ISSUE TITLE
Create Documentation for instances

### ISSUE THREAD

**Issue by Gravy59** [ChaosInitiative/P2CE-Instances#1]
I believe that documentation is very important here so that no one gets confused and/or has questions. I'm giving it a go right now but it is a bit tiresome so if I had some pointers or something I would appreciate it. Thanks.
-Gravy
P.S. ***Completely off topic***
A few questions:
Are these instances compatible with the Portal 2 Hammer Editor? I want to make a mod in P2CE but will make it in normal P2 for the time being until it comes out.
Speaking of which, when can I get access to the engine to have my mod "official"?
What is your licensing policy on mods?

**Comment by JJL772** [comment]
> I believe that documentation is very important here so that no one gets confused and/or has questions. I'm giving it a go right now but it is a bit tiresome so if I had some pointers or something I would appreciate it. Thanks.

I guess we could, but I don't think it's too difficult to use these. We're pretty busy as of late with more important stuff so don't hold your breath on docs. 

>  Are these instances compatible with the Portal 2 Hammer Editor? I want to make a mod in P2CE but will make it in normal P2 for the time being until it comes out.

Some *might* be, but don't count on it. 

>  Speaking of which, when can I get access to the engine to have my mod "official"?
>  What is your licensing policy on mods?

You don't need engine access for your mod to be "official". My suggestion is to get a steam page for your mod, at which point it's as "official" as it can be. 

Also, we don't handle licensing, valve does that, so contact them.

**Comment by Gravy59** [comment]
Thanks. I tested the elevator and some things are broken - it wants some VScript or something like that and the portal emitter is just a bunch of errors.

**Comment by JJL772** [comment]
I think #2 fixes that, haven't tried it out myself yet though
