### ISSUE TITLE
Suggestion: Trophy Stand

### ISSUE THREAD

**Issue by C-Husky** [ChaosInitiative/P2CE-Instances#8]
![image](https://user-images.githubusercontent.com/111747332/185912805-85fbf9d2-03d3-4c5f-a5f5-623c34c2a9f3.png)
![image](https://user-images.githubusercontent.com/111747332/185913732-da3d45cf-c551-47d6-b197-613ee4919775.png)
**Decompiled** it, apply **glass textures** manually. (For some reason, the **glass texture doesnt show itself**.)

**Comment by AWildErin** [comment]
This isn't really something that's exactly going to be useful in our instances repo. If we open a prefab repo in the future, maybe? But it really isn't something useful as an instance for p2ce
